name: Make Recovery

on:
  watch:
    types: [started]
    
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Clean Up
      run: |
        echo "Wait for a while."
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
      
    - name: Install packages
      run: |
        sudo apt -y upgrade
        
    - name: Install required packages
      run: sudo apt -y install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev imagemagick libbz2-dev libssl-dev lzma ncftp bash-completion python openjdk-8-jdk qemu-user-static
      
    - name: Set variables
      run: |
        echo "::set-output name=twrp_url::$(jq -r '.twrp_url' config.json)"
        echo "::set-output name=twrp_branch::$(jq -r '.twrp_branch' config.json)"
        echo "::set-output name=git_username::$(jq -r '.git_username' config.json)"
        echo "::set-output name=git_email::$(jq -r '.git_email' config.json)"
        echo "::set-output name=use_own_dt::$(jq -r '.use_own_dt' config.json)"
        echo "::set-output name=dt_url::$(jq -r '.dt_url' config.json)"
        echo "::set-output name=dt_remote::$(jq -r '.dt_remote' config.json)"
        echo "::set-output name=dt_branch::$(jq -r '.dt_branch' config.json)"
        echo "::set-output name=dt_path::$(jq -r '.dt_path' config.json)"
        echo "::set-output name=device_code::$(jq -r '.device_code' config.json)"
        echo "::set-output name=use_repair_manifest::$(jq -r '.use_repair_manifest' config.json)"
        echo "::set-output name=fix_product::$(jq -r '.fix_product' config.json)"
        echo "::set-output name=fix_misscom::$(jq -r '.fix_misscom' config.json)"
        echo "::set-output name=fix_busybox::$(jq -r '.fix_busybox' config.json)"
        echo "::set-output name=fix_branch::$(jq -r '.fix_branch' config.json)"
        echo "::set-output name=use_omin_head::$(jq -r '.use_omin_head' config.json)"
        echo "::set-output name=use_customize_mode::$(jq -r '.use_customize_mode' config.json)"
        echo "::set-output name=customize_name::$(jq -r '.customize_name' config.json)"
        echo "::set-output name=use_advanced_mode::$(jq -r '.use_advanced_mode' config.json)"
        echo "::set-output name=advanced_name::$(jq -r '.advanced_name' config.json)"
        echo "::set-output name=date::$(date +%F)"
      id: var
      
    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH
        
    - name: Initialize Repair Manifest
      if: steps.var.outputs.use_repair_manifest == 'true'
      run: git clone https://github.com/TeamWin/buildtree_manifests.git repair/
      
    - name: Initialize a Repo client
      run: |
        echo "The automatic repair option is turned off, so the Repair Manifest will not be pulled."
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "::set-output name=pwd::$(pwd)"
        git config --global user.name "${{ steps.var.outputs.git_username }}"
        git config --global user.email "${{ steps.var.outputs.git_email }}"
        repo init --depth=1 -u ${{ steps.var.outputs.twrp_url }} -b ${{ steps.var.outputs.twrp_branch }}
        mkdir .repo/local_manifests
      id: pwd
      
    - name: Fix the bug of missing common
      if: steps.var.outputs.use_repair_manifest == 'true' && steps.var.outputs.fix_misscom == 'true'
      run: cp repair/omni-9.0/qcom.xml workspace/.repo/local_manifests/
      
    - name: Fix busybox bug
      if: steps.var.outputs.use_repair_manifest == 'true' && steps.var.outputs.fix_busybox == 'true'
      run: cp repair/omni-9.0/busybox.xml workspace/.repo/local_manifests/
      
    - name: Clone your own device tree
      if: steps.var.outputs.use_own_dt == 'true'
      run: |
        sed -i 's!dt_url!${{ steps.var.outputs.dt_url }}!g' device.xml
        sed -i 's!dt_path!${{ steps.var.outputs.dt_path }}!g' device.xml
        sed -i 's!dt_remote!${{ steps.var.outputs.dt_remote }}!g' device.xml
        sed -i 's!dt_branch!${{ steps.var.outputs.dt_branch }}!g' device.xml
        cp device.xml workspace/.repo/local_manifests/ 
          
    - name: Sync from manifest
      run: |
        PATH=~/bin:$PATH
        cd workspace
        repo sync -j$(nproc --all) -f --force-sync
        ls -al
        
    - name: Fix cannot locate product
      if: steps.var.outputs.use_repair_manifest == 'true' && steps.var.outputs.fix_product == 'true'
      run: |
        cd ${{ steps.pwd.outputs.pwd }}/build/core
        rm -rf product_config.mk
        sed -i 's!device_code!${{ steps.var.outputs.device_code }}!g' ${{ steps.pwd.outputs.pwd }}/../build/core/${{ steps.var.outputs.fix_branch }}/product_config.mk
        cp ${{ steps.pwd.outputs.pwd }}/../build/core/${{ steps.var.outputs.fix_branch }}/product_config.mk ${{ steps.pwd.outputs.pwd }}/build/core/product_config.mk
      
    - name: Start Building (Normal Mode)
      if: steps.var.outputs.use_omin_head == 'false'
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        tree ./device
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ steps.var.outputs.device_code }}-eng 
        make clean & make recoveryimage -j$(nproc --all)
        
    - name: Start Building (Omni Mode)
      if: steps.var.outputs.use_omin_head == 'true'
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        tree ./device
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_${{ steps.var.outputs.device_code }}-eng 
        make clean & make recoveryimage -j$(nproc --all)    
        
    - name: Start Building (Customize Mode)
      if: steps.var.outputs.use_customize_mode == 'true'
       run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        tree ./device
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch {{ steps.var.outputs.customize_name }}
        make clean & make recoveryimage -j$(nproc --all)
        
    - name: Start Building (Advanced Mode)
      if: steps.var.outputs.use_advanced_mode == 'true'
       run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        tree ./device
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch {{ steps.var.outputs.customize_name }}
        make clean & make {{ steps.var.outputs.advanced_name }} -j$(nproc --all)

      
    - name: Upload File to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ steps.var.outputs.device_code }}/recovery.img
        name: ${{ steps.var.outputs.date }} ${{ steps.var.outputs.device_code }} by ${{ steps.var.outputs.git_username }}
        tag_name: ${{ github.run_id }}
        body: TWRP Recovery built by ${{ steps.var.outputs.git_username }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
